import type { INodeProperties } from 'n8n-workflow';

const GATE_OPTIONS = [
	{ name: 'Barrier', value: 'barrier' },
	{ name: 'CCX / Toffoli', value: 'ccx' },
	{ name: 'CNOT / CX', value: 'cx' },
	{ name: 'Controlled RX', value: 'crx' },
	{ name: 'Controlled RY', value: 'cry' },
	{ name: 'Controlled RZ', value: 'crz' },
	{ name: 'CZ', value: 'cz' },
	{ name: 'Hadamard', value: 'h' },
	{ name: 'Identity', value: 'id' },
	{ name: 'Measure', value: 'measure' },
	{ name: 'Phase', value: 'p' },
	{ name: 'Reset', value: 'reset' },
	{ name: 'RX', value: 'rx' },
	{ name: 'RY', value: 'ry' },
	{ name: 'RZ', value: 'rz' },
	{ name: 'S', value: 's' },
	{ name: 'S Dagger', value: 'sdg' },
	{ name: 'Swap', value: 'swap' },
	{ name: 'T', value: 't' },
	{ name: 'T Dagger', value: 'tdg' },
	{ name: 'U', value: 'u' },
	{ name: 'X', value: 'x' },
	{ name: 'Y', value: 'y' },
	{ name: 'Z', value: 'z' },
];

const SUBMIT_OPS = ['submitSampler', 'submitEstimator'];

export const nodeProperties: INodeProperties[] = [
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'Account', value: 'account' },
			{ name: 'Backend', value: 'backend' },
			{ name: 'Circuit', value: 'circuit' },
			{ name: 'Job', value: 'job' },
			{ name: 'Session', value: 'session' },
		],
		default: 'job',
	},

	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['account'] } },
		options: [
			{ name: 'Get Instance', value: 'getInstance', action: 'Get the current instance details' },
			{ name: 'Get Usage', value: 'getUsage', action: 'Get instance usage and allocation' },
		],
		default: 'getUsage',
	},

	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['backend'] } },
		options: [
			{ name: 'Get Configuration', value: 'getConfiguration', action: 'Get backend configuration' },
			{ name: 'Get Least Busy', value: 'getLeastBusy', action: 'Get the least busy backend' },
			{ name: 'Get Properties', value: 'getProperties', action: 'Get backend properties' },
			{ name: 'Get Status', value: 'getStatus', action: 'Get backend status' },
			{ name: 'List', value: 'list', action: 'List available backends' },
		],
		default: 'list',
	},

	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['circuit'] } },
		options: [
			{ name: 'Build', value: 'build', action: 'Build a circuit from gates' },
			{ name: 'Import OpenQASM 3', value: 'import', action: 'Import an existing OpenQASM 3 circuit' },
		],
		default: 'build',
	},

	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['job'] } },
		options: [
			{ name: 'Cancel', value: 'cancel', action: 'Cancel a job' },
			{ name: 'Delete', value: 'delete', action: 'Delete a job' },
			{ name: 'Get Results', value: 'getResults', action: 'Poll until the job finishes, then retrieve its results' },
			{ name: 'Get Status', value: 'getStatus', action: 'Get the status of a job' },
			{ name: 'List', value: 'list', action: 'List recent jobs' },
			{ name: 'Submit to Estimator', value: 'submitEstimator', action: 'Submit a circuit to the Estimator primitive' },
			{ name: 'Submit to Sampler', value: 'submitSampler', action: 'Submit a circuit to the Sampler primitive' },
		],
		default: 'submitSampler',
	},

	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['session'] } },
		options: [
			{ name: 'Close', value: 'close', action: 'Close a session' },
			{ name: 'Create', value: 'create', action: 'Create a session or batch' },
			{ name: 'Get', value: 'get', action: 'Get a session' },
			{ name: 'Set Accepting Jobs', value: 'setAccepting', action: 'Set whether the session accepts new jobs' },
		],
		default: 'create',
	},

	{
		displayName: 'Backend Name',
		name: 'backendName',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'ibm_brisbane',
		description:
			'Name of the backend (a specific quantum device or simulator) to query, e.g. ibm_brisbane. Use the Backend List operation to see available names.',
		displayOptions: {
			show: { resource: ['backend'], operation: ['getConfiguration', 'getProperties', 'getStatus'] },
		},
	},
	{
		displayName: 'Minimum Qubits',
		name: 'minQubits',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Only consider backends with at least this many qubits. Zero disables the filter.',
		displayOptions: { show: { resource: ['backend'], operation: ['getLeastBusy'] } },
	},
	{
		displayName: 'Include Simulators',
		name: 'includeSimulators',
		type: 'boolean',
		default: false,
		description: 'Whether to include simulators when selecting the least busy backend',
		displayOptions: { show: { resource: ['backend'], operation: ['getLeastBusy'] } },
	},

	{
		displayName: 'Number of Qubits',
		name: 'numQubits',
		type: 'number',
		typeOptions: { minValue: 1 },
		required: true,
		default: 2,
		description: 'Size of the quantum register',
		displayOptions: { show: { resource: ['circuit'], operation: ['build'] } },
	},
	{
		displayName: 'Number of Classical Bits',
		name: 'numClbits',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 2,
		description: 'Size of the classical register used for measurement',
		displayOptions: { show: { resource: ['circuit'], operation: ['build'] } },
	},
	{
		displayName: 'Gates',
		name: 'gates',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true, sortable: true },
		default: {},
		placeholder: 'Add Gate',
		displayOptions: { show: { resource: ['circuit'], operation: ['build'] } },
		options: [
			{
				name: 'gate',
				displayName: 'Gate',
				values: [
					{
						displayName: 'Gate',
						name: 'gate',
						type: 'options',
						default: 'h',
						options: GATE_OPTIONS,
						description: 'Gate or instruction to append',
					},
					{
						displayName: 'Qubits',
						name: 'qubits',
						type: 'string',
						required: true,
						default: '',
						placeholder: '0 or 0,1 or 0,1,2',
						description:
							'Comma-separated qubit indices. For controlled gates the control comes first and the target last (e.g. 0,1 = control 0, target 1). Leave empty only for a full-width barrier.',
					},
					{
						displayName: 'Parameters',
						name: 'params',
						type: 'string',
						default: '',
						placeholder: '1.5708 or 0.1,0.2,0.3',
						description:
							'Comma-separated angles in radians. One value for RX/RY/RZ/Phase/Controlled-R gates; exactly three (theta, phi, lambda) for the U gate.',
						displayOptions: { show: { gate: ['rx', 'ry', 'rz', 'p', 'crx', 'cry', 'crz', 'u'] } },
					},
					{
						displayName: 'Classical Bit',
						name: 'clbit',
						type: 'number',
						typeOptions: { minValue: 0 },
						default: 0,
						description: 'Target classical bit for the measure instruction',
						displayOptions: { show: { gate: ['measure'] } },
					},
				],
			},
		],
	},

	{
		displayName: 'OpenQASM 3 Circuit',
		name: 'qasm3Input',
		type: 'string',
		typeOptions: { rows: 8 },
		required: true,
		default: '',
		description: 'An existing OpenQASM 3 program to pass through',
		displayOptions: { show: { resource: ['circuit'], operation: ['import'] } },
	},

	{
		displayName: 'Backend',
		name: 'backend',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'ibm_brisbane',
		description: 'Backend that will run the circuit. The circuit must already be transpiled (ISA) for this backend; the Qiskit Runtime API does not transpile and rejects non-native circuits.',
		displayOptions: { show: { resource: ['job'], operation: SUBMIT_OPS } },
	},
	{
		displayName: 'OpenQASM 3 Circuit',
		name: 'qasm3',
		type: 'string',
		typeOptions: { rows: 8 },
		required: true,
		default: '',
		description: 'Circuit to submit, as an ISA (backend-native) OpenQASM 3 string. Use an expression to reference a Circuit node output.',
		displayOptions: { show: { resource: ['job'], operation: SUBMIT_OPS } },
	},
	{
		displayName: 'Parameters',
		name: 'parameters',
		type: 'json',
		default: '',
		placeholder: '{ "theta": 1.5708 }',
		description:
			'Optional bindings for a parametrized circuit, as a JSON object mapping parameter names to values (or arrays of values). Leave empty for a fixed circuit.',
		displayOptions: { show: { resource: ['job'], operation: SUBMIT_OPS } },
	},
	{
		displayName: 'Shots',
		name: 'shots',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 1024,
		description: 'Number of repetitions of the circuit',
		displayOptions: { show: { resource: ['job'], operation: ['submitSampler'] } },
	},
	{
		displayName: 'Observables',
		name: 'observables',
		type: 'json',
		default: '"ZZ"',
		description:
			'Quantity the Estimator measures, written as a Pauli string of the letters I, X, Y and Z (one per qubit, e.g. "ZZ"). Provide a single string or a JSON array of strings; each must match the number of qubits in the circuit (the length is validated by IBM at submit time).',
		displayOptions: { show: { resource: ['job'], operation: ['submitEstimator'] } },
	},
	{
		displayName: 'Resilience Level',
		name: 'resilienceLevel',
		type: 'options',
		options: [
			{ name: '0 (No Error Mitigation)', value: 0 },
			{ name: '1 (Minimal)', value: 1 },
			{ name: '2 (Medium)', value: 2 },
		],
		default: 1,
		description: 'Error mitigation level applied by the Estimator. Higher levels reduce noise at the cost of more runtime.',
		displayOptions: { show: { resource: ['job'], operation: ['submitEstimator'] } },
	},
	{
		displayName: 'Precision',
		name: 'precision',
		type: 'number',
		typeOptions: { minValue: 0, numberPrecision: 6 },
		default: 0,
		description: 'Target precision for the Estimator. Leave at 0 to use the backend default.',
		displayOptions: { show: { resource: ['job'], operation: ['submitEstimator'] } },
	},
	{
		displayName: 'Dynamical Decoupling',
		name: 'dynamicalDecoupling',
		type: 'boolean',
		default: false,
		description: 'Whether to apply dynamical decoupling to idle qubits to reduce decoherence noise',
		displayOptions: { show: { resource: ['job'], operation: SUBMIT_OPS } },
	},
	{
		displayName: 'Gate Twirling',
		name: 'twirlingGates',
		type: 'boolean',
		default: false,
		description: 'Whether to apply Pauli twirling to gates to suppress coherent errors',
		displayOptions: { show: { resource: ['job'], operation: SUBMIT_OPS } },
	},
	{
		displayName: 'Measurement Twirling',
		name: 'twirlingMeasure',
		type: 'boolean',
		default: false,
		description: 'Whether to apply twirling to measurements to suppress readout errors',
		displayOptions: { show: { resource: ['job'], operation: SUBMIT_OPS } },
	},
	{
		displayName: 'Session ID',
		name: 'submitSessionId',
		type: 'string',
		default: '',
		description:
			'Optional session or batch ID (from Session Create) to run this job inside, for low-latency consecutive execution',
		displayOptions: { show: { resource: ['job'], operation: SUBMIT_OPS } },
	},
	{
		displayName: 'Additional Options',
		name: 'additionalOptions',
		type: 'json',
		default: '{}',
		description:
			'Advanced JSON options passed straight to the primitive, for example {"default_shots": 4096}. Most workflows can leave this as {}. See the IBM Qiskit Runtime primitive options documentation.',
		displayOptions: { show: { resource: ['job'], operation: SUBMIT_OPS } },
	},

	{
		displayName: 'Job ID',
		name: 'jobId',
		type: 'string',
		required: true,
		default: '',
		description:
			'ID of the job to act on, as returned by the Submit operation. Usually set with an expression referencing a previous IBM Quantum node.',
		displayOptions: {
			show: { resource: ['job'], operation: ['getStatus', 'getResults', 'cancel', 'delete'] },
		},
	},
	{
		displayName: 'Poll Interval (Seconds)',
		name: 'pollInterval',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 5,
		description: 'Seconds to wait between status checks while the job runs',
		displayOptions: { show: { resource: ['job'], operation: ['getResults'] } },
	},
	{
		displayName: 'Max Wait (Seconds)',
		name: 'maxWait',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 300,
		description:
			'Maximum seconds to wait for the job to finish. Real hardware queues can be long, so raise this for production runs or poll separately with Get Status.',
		displayOptions: { show: { resource: ['job'], operation: ['getResults'] } },
	},
	{
		displayName: 'Register Name',
		name: 'registerName',
		type: 'string',
		default: '',
		description: 'Optional classical register name to read counts from. Detected automatically when empty.',
		displayOptions: { show: { resource: ['job'], operation: ['getResults'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['job'], operation: ['list'] } },
	},

	{
		displayName: 'Mode',
		name: 'mode',
		type: 'options',
		options: [
			{ name: 'Batch', value: 'batch' },
			{ name: 'Dedicated', value: 'dedicated' },
		],
		default: 'batch',
		description:
			'Batch queues jobs to run consecutively without interactive priority, and is the only mode the Open (free) plan allows. Dedicated reserves the QPU for back-to-back jobs (best for VQE and QAOA loops) and requires a paid plan.',
		displayOptions: { show: { resource: ['session'], operation: ['create'] } },
	},
	{
		displayName: 'Backend',
		name: 'sessionBackend',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'ibm_brisbane',
		description: 'Backend the session reserves for its jobs',
		displayOptions: { show: { resource: ['session'], operation: ['create'] } },
	},
	{
		displayName: 'Max TTL (Seconds)',
		name: 'maxTtl',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 28800,
		description: 'Maximum session lifetime in seconds. The default is 28800 (8 hours).',
		displayOptions: { show: { resource: ['session'], operation: ['create'] } },
	},
	{
		displayName: 'Session ID',
		name: 'sessionId',
		type: 'string',
		required: true,
		default: '',
		description: 'ID of the session, as returned by Session Create',
		displayOptions: { show: { resource: ['session'], operation: ['get', 'setAccepting', 'close'] } },
	},
	{
		displayName: 'Accepting Jobs',
		name: 'acceptingJobs',
		type: 'boolean',
		default: true,
		description:
			'Whether the session keeps accepting new jobs. Set to false to stop it taking work; it closes once running jobs finish.',
		displayOptions: { show: { resource: ['session'], operation: ['setAccepting'] } },
	},
];
